"""add duel ready columns

Revision ID: 11340bdf1dd7
Revises: aa73bee23b8b
Create Date: 2026-08-31 17:39:57.605737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11340bdf1dd7'
down_revision: Union[str, Sequence[str], None] = 'aa73bee23b8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('duels', sa.Column('player1_ready', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('duels', sa.Column('player2_ready', sa.Boolean(), server_default='false', nullable=False))
    op.create_check_constraint('ck_duel_status_valid', 'duels', "status IN ('pending', 'ready', 'active', 'finished', 'abandoned')")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_duel_status_valid', 'duels', type_='check')
    op.drop_column('duels', 'player2_ready')
    op.drop_column('duels', 'player1_ready')
    # ### end Alembic commands ###
