"""add duel self-duel check and server defaults

Revision ID: 7637d486c93e
Revises: 9f571d02baec
Create Date: 2026-08-30 12:36:59.075830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7637d486c93e'
down_revision: Union[str, Sequence[str], None] = '9f571d02baec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint('ck_duel_players_distinct', 'duels', 'player1_id != player2_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_duel_players_distinct', 'duels', type_='check')
    # ### end Alembic commands ###
